language: c
compiler:
  - gcc
#  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libcurl4-openssl-dev
script: cd c && ./configure && make

notifications:
  irc: "irc.freenode.net#eam"

